---
- name: install ruby
  pacman:
    name: ruby
    state: present
- name: install rust
  pacman:
    name: rust
    state: present
- name: install clojure
  pacman:
    name: clojure
    state: present
- name: install clj-kondo-bin
  aur:
    name: clj-kondo-bin
    use: auto
    state: present
  become: no
- name: install go
  pacman:
    name: go
    state: present
- name: install zig
  pacman:
    name: zig
    state: present
- name: install code
  pacman:
    name: code
    state: present
- name: install vim
  pacman:
    name: vim
    state: present
- name: install neovim
  aur: name=neovim-nightly use=auto state=present
  become: no
- name: install emacs
  aur: name=emacs use=auto state=present
  become: no
- name: install yarn
  pacman:
    name: yarn
    state: present
- name: install npm
  pacman:
    name: npm
    state: present
- name: install jre8-openjdk
  pacman:
    name: jre8-openjdk
    state: present
- name: install python stuff
  pacman:
    name: python-oauth2client, python-pip, python-pipenv, python-pyinotify
    state: present
- name: install stack
  pacman:
    name: stack
    state: present
- name: install perl
  pacman:
    name: perl
    state: present
