---
- name: install reflector
  pacman:
    name: reflector
    state: present
- name: update mirrors
  command: reflector --country Brazil --protocol https --sort rate --save /etc/pacman.d/mirrorlist
  register: mirrors_updated
- name: update
  pacman:
    update_cache: yes
  when:
    mirrors_updated['failed'] == false
- name: install base-devel
  pacman:
    name: base-devel
    state: present
- name: install git
  pacman:
    name: git
    state: present
- name: ls yay
  shell: ls yay/
  ignore_errors: yes
  register: yay_downloaded
- name: clone yay
  command: git clone https://aur.archlinux.org/yay.git 
  become: no
  when: yay_downloaded['failed'] == true
- name: install yay
  aur: name=yay use=makepkg state=present
  become: no
