---
- name: install pgcli
  aur: name=pgcli use=yay state=present
  become: no
- name: install dbeaver
  pacman:
    name: dbeaver
    state: present
- name: install postgresql
  pacman:
    name: postgresql
    state: present
