---
- name: install libvirt
  pacman:
    name: libvirt
    state: present
- name: install qemu
  pacman:
    name: qemu
    state: present
- name: install virt-manager
  pacman:
    name: virt-manager
    state: present    
# enabled copy and paste support in a guest virtual machine
- name: install spice-vdagent
  pacman:
    name: spice-vdagent
    state: present    
