---
- name: install libvirt
  pacman:
    name: libvirt
    state: present
- name: install qemu
  pacman:
    name: qemu
    state: present
- name: install virt-manager
  pacman:
    name: virt-manager
    state: present    
- name: install vagrant
  pacman:
    name: vagrant
    state: present    
- name: install docker
  pacman:
    name: docker
    state: present    
- name: install docker-compose
  pacman:
    name: docker-compose
    state: present    
- name: install terraform
  pacman:
    name: terraform
    state: present    
# enabled copy and paste support in a guest virtual machine
#- name: install spice-vdagent
#  pacman:
#    name: spice-vdagent
#    state: present    
